-- crear tabla para eventos
DROP TABLE IF EXISTS redes_afinidad.eventos;
CREATE TABLE redes_afinidad.eventos (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre text,
  categoria text,
  fecha date DEFAULT CURRENT_DATE,
  horadeinicio timestamp DEFAULT now(),
  horadefin timestamp DEFAULT now(),
  ubicacion text,
  capacidadmaxima int
);
ALTER TABLE redes_afinidad.eventos OWNER TO mtonelli;

ALTER TABLE redes_afinidad.eventos
ALTER COLUMN id DROP IDENTITY;

ALTER TABLE redes_afinidad.eventos
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- crear tabla temporal para sincronizar eventos
CREATE FOREIGN TABLE eventos_origen (
  id int,
  nombre text,
  categoria text,
  fecha date,
  horadeinicio timestamp,
  horadefin timestamp,
  ubicacion text,
  capacidadmaxima int
)
SERVER origen_db
OPTIONS (schema_name 'public', table_name 'eventos');


-- sincronizar eventos
-- 1. UPSERT (INSERT + UPDATE)
INSERT INTO redes_afinidad.eventos (
  id, nombre, categoria, fecha,
  horadeinicio, horadefin, ubicacion, capacidadmaxima
)
-- OVERRIDING SYSTEM VALUE
SELECT
  id, nombre, categoria, fecha,
  horadeinicio, horadefin, ubicacion, capacidadmaxima
FROM eventos_origen
ON CONFLICT (id)
DO UPDATE SET
  nombre = EXCLUDED.nombre,
  categoria = EXCLUDED.categoria,
  fecha = EXCLUDED.fecha,
  horadeinicio = EXCLUDED.horadeinicio,
  horadefin = EXCLUDED.horadefin,
  ubicacion = EXCLUDED.ubicacion,
  capacidadmaxima = EXCLUDED.capacidadmaxima;

-- 2. DELETE sincronizado
DELETE FROM redes_afinidad.eventos d
WHERE NOT EXISTS (
  SELECT 1 FROM eventos_origen o
  WHERE o.id = d.id
);



--cron para sincronizar eventos
SELECT cron.schedule(
  'sync_eventos',
  '* * * * *',  -- cada 1 minuto (mínimo estándar)
  $$
  -- UPSERT
  INSERT INTO redes_afinidad.eventos (
    id, nombre, categoria, fecha,
    horadeinicio, horadefin, ubicacion, capacidadmaxima
  )
  SELECT
    id, nombre, categoria, fecha,
    horadeinicio, horadefin, ubicacion, capacidadmaxima
  FROM eventos_origen
  ON CONFLICT (id)
  DO UPDATE SET
    nombre = EXCLUDED.nombre,
    categoria = EXCLUDED.categoria,
    fecha = EXCLUDED.fecha,
    horadeinicio = EXCLUDED.horadeinicio,
    horadefin = EXCLUDED.horadefin,
    ubicacion = EXCLUDED.ubicacion,
    capacidadmaxima = EXCLUDED.capacidadmaxima;

  -- DELETE
  DELETE FROM redes_afinidad.eventos d
  WHERE NOT EXISTS (
    SELECT 1 FROM eventos_origen o
    WHERE o.id = d.id
  );
  $$
);


