--crear tabla para instagram comentarios
DROP TABLE IF EXISTS redes_sociales.instagram_comentarios;
CREATE TABLE redes_sociales.instagram_comentarios (
  key_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comentario_id TEXT NOT NULL,
  post_id BIGINT NOT NULL,
  username TEXT,
  comentario TEXT,
  sentimiento TEXT,
  fecha_creacion TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE redes_sociales.instagram_comentarios OWNER TO mtonelli;


-- crear tabla temporal para sincronizar instagram comentarios
DROP FOREIGN TABLE IF EXISTS instagram_comentarios_origen;
CREATE FOREIGN TABLE instagram_comentarios_origen (
  comentario_id text,
  post_id bigint,
  username text,
  comentario text,
  sentimiento text,
  fecha_creacion text,
  key_id bigint,
  created_at timestamptz,
  updated_at timestamptz
)
SERVER origen_db
OPTIONS (schema_name 'public', table_name 'Instagram_comentarios');

-- insertar instagram comentarios en la tabla temporal
INSERT INTO redes_sociales.instagram_comentarios (
  key_id,
  comentario_id,
  post_id,
  username,
  comentario,
  sentimiento,
  fecha_creacion,
  created_at,
  updated_at
)
SELECT
  key_id,
  comentario_id,
  post_id,
  username,
  comentario,
  sentimiento,
  NULLIF(fecha_creacion, '')::timestamptz,
  created_at,
  updated_at
FROM instagram_comentarios_origen
ON CONFLICT (key_id)
DO UPDATE SET
  comentario_id = EXCLUDED.comentario_id,
  post_id = EXCLUDED.post_id,
  username = EXCLUDED.username,
  comentario = EXCLUDED.comentario,
  sentimiento = EXCLUDED.sentimiento,
  fecha_creacion = EXCLUDED.fecha_creacion,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

  DELETE FROM redes_sociales.instagram_comentarios d
WHERE NOT EXISTS (
  SELECT 1
  FROM instagram_comentarios_origen o
  WHERE o.key_id = d.key_id
);

-- cron para sincronizar instagram comentarios
SELECT cron.schedule(
  'sync_instagram_comentarios',
  '* * * * *',  -- cada minuto
  $$
  INSERT INTO redes_sociales.instagram_comentarios (
  key_id,
  comentario_id,
  post_id,
  username,
  comentario,
  sentimiento,
  fecha_creacion,
  created_at,
  updated_at
)
SELECT
  key_id,
  comentario_id,
  post_id,
  username,
  comentario,
  sentimiento,
  NULLIF(fecha_creacion, '')::timestamptz,
  created_at,
  updated_at
FROM instagram_comentarios_origen
ON CONFLICT (key_id)
DO UPDATE SET
  comentario_id = EXCLUDED.comentario_id,
  post_id = EXCLUDED.post_id,
  username = EXCLUDED.username,
  comentario = EXCLUDED.comentario,
  sentimiento = EXCLUDED.sentimiento,
  fecha_creacion = EXCLUDED.fecha_creacion,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

  DELETE FROM redes_sociales.instagram_comentarios d
  WHERE NOT EXISTS (
    SELECT 1 FROM instagram_comentarios_origen o
    WHERE o.key_id = d.key_id
  );
  $$
);