-- Aplicar en el PostgreSQL del chatbot (redes-afinidad_db-chatbot)
-- Crea y puebla la tabla de operadores para la sección Estructura Territorial.

CREATE TABLE IF NOT EXISTS usuarios_territoriales (
  id           BIGSERIAL    PRIMARY KEY,
  nombre       TEXT         NOT NULL,
  celular      TEXT,
  tipo_usuario TEXT,        -- enlace | regional | estatal | vocal | promotor
  programa     TEXT,        -- CSV: "COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR"
  municipio    TEXT,
  localidad    TEXT,
  superior_id  BIGINT       REFERENCES usuarios_territoriales(id) ON DELETE SET NULL,
  activo       BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ut_tipo     ON usuarios_territoriales (tipo_usuario);
CREATE INDEX IF NOT EXISTS idx_ut_programa ON usuarios_territoriales (programa);
CREATE INDEX IF NOT EXISTS idx_ut_celular  ON usuarios_territoriales (celular);

-- ── Datos iniciales (Listado de usuarios con Rol) ─────────────────────────
-- Fuente: "Listado de usuarios con Rol.pdf"
-- tipo_usuario en minúsculas para coincidir con el frontend

INSERT INTO usuarios_territoriales (nombre, celular, tipo_usuario, programa) VALUES
-- ── ENLACES — Programas: COINVERSIÓN SOCIAL + CONTIGO ESTAMOS MEJOR ──────
('BRIGITTE RAMIREZ CORTEZ',           '4427763862', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('TORIBIA ESCAMILLA RIOS',            '4412131636', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('ARMANDO ALVARADO MARTÍNEZ',         '4411012824', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('ALMA TREJO VEGA',                   '4191083097', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('SANDRA VERÓNICA JUÁREZ ARZATE',     '5614810373', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('DANIEL TREJO PINEDA',               '4421556319', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('LORENA RODRIGUEZ HERNANDEZ',        '4424381220', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('MARIA DEL CARMEN DIAZ MARTINEZ',    '4411372182', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('ANA ALVAREZ',                       '4412769093', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('MONTSERRAT MANDUJANO DEL CASTILLO', '4424483796', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('JORGE ALBERTO CORDOVA CORDOVA',     '4481136792', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('YUSELIM GUDIÑO',                    '4412033514', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('NANCY KARINA OLVERA RESENDIZ',      '4411388087', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('LUCERO HERNÁNDEZ CÓRDOBA',          '4426095749', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('DOLORES MARIÑO SANCHEZ',            '4428771203', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('ALEJANDRO RODRIGUEZ',               '4421277868', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('J CESAR MEDELLIN FRANCO',           '4411009595', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('MARTHA FABIOLA LÓPEZ MONTIEL',      '4271820174', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('JOSÉ MANUEL HERNÁNDEZ GONZÁLEZ',    '4142319872', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('ANA LILIA RINCÓN',                  '4411194402', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),

-- ── ENLACES — Programas: CONTIGO Y TU BEBÉ + CONTIGO EN TU MESA ──────────
('JUAN HUGO LEDESMA CABRERA',         '4411166453', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('OSCAR SORIA UGALDE',                '5572942913', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('ASAEL MARTÍNEZ VILCHIS',            '4421544422', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('ROGER DE LA ROSA RODRÍGUEZ',        '4411191484', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('BRENDA MORALES MOYA',               '4422324063', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('ISAIAS GUTIERREZ BARRERA',          '4291179472', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('MARIELA GARCÍA ORDOÑEZ',            '4481044405', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('ROMEO MARQUES FONSECA',             '4411204321', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('JORGE RICARDO ERREGUIN ANDRADE',    '4411166453', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('VIOLETA BARRÓN SIXTOS',             '4425946624', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('ROMÁN SÁNCHEZ MARTÍNEZ',            '4411001121', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('JOSÉ NOEL MEDINA ZARATE',           '4412659431', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),

-- ── ENLACES (continuación, pág. 2) ───────────────────────────────────────
('JUAN CARLOS MATÍAS',                '4271684494', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('JOSÉ ANTONIO PIÑA OSORNIO',         '4271127590', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('MAGALY BARRÓN SIXTOS',              '4481763846', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('MARÍA FERNANDA ESPINOZA LEÓN',      '4428748314', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('GUADALUPE DÍAZ RODRÍGUEZ',          '4421776331', 'enlace',   'CONTIGO ESTAMOS MEJOR, COINVERSIÓN SOCIAL'),
('MARCOS CAMPOS ALCANTAR',            '4421284456', 'enlace',   'COINVERSIÓN SOCIAL, CONTIGO EN TU MESA'),
('LORENA ARELY GARIBAY RODRÍGUEZ',    '4427480522', 'enlace',   'CONTIGO EN TU MESA, COINVERSIÓN SOCIAL'),
('JUAN RESÉNDIZ MORALES',             '4428075512', 'enlace',   'CONTIGO EN TU MESA, CONTIGO ESTAMOS MEJOR'),
('DIEGO ENRIQUE RANGEL BERNAL',       '4423764405', 'enlace',   'CONTIGO EN TU MESA'),
('MARÍA GUADALUPE BAEZA HERNÁNDEZ',   '4423272919', 'enlace',   'CONTIGO EN TU MESA, CONTIGO Y TU BEBÉ'),
('REGINA ROMERO SÁNCHEZ',             '4427788796', 'enlace',   'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),

-- ── REGIONALES ────────────────────────────────────────────────────────────
('RICARDO MARTÍNEZ GAYOU',            '4421542083', 'regional', 'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('JOSÉ ABRAHAM AGUILA ALONSO',        '4428494904', 'regional', 'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),

-- ── ESTATALES ─────────────────────────────────────────────────────────────
('JUAN PABLO MEJÍA BARRAZA',          '4421793429', 'estatal',  'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('HERMANN ANTONIO PFEIFFER MARTÍNEZ', '4421879453', 'estatal',  'CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('HUGO GONZALEZ SANTIAGO',            '4424394908', 'estatal',  'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('CAROLINA SALAZAR CHAVEZ',           '4411102331', 'estatal',  'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR'),
('EMMANUEL MARTÍNEZ HERNÁNDEZ',       '4425197267', 'estatal',  'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR, CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA'),
('ROSALBA GABRIELA ABARCA ACEVEDO',   '7471482193', 'estatal',  'COINVERSIÓN SOCIAL, CONTIGO ESTAMOS MEJOR, CONTIGO Y TU BEBÉ, CONTIGO EN TU MESA')

ON CONFLICT DO NOTHING;
